/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const T = IDL.Record({
  'completed' : IDL.Bool,
  'level' : IDL.Nat,
  'stars' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addCoins' : IDL.Func([IDL.Nat], [], []),
  'buyDetector' : IDL.Func([], [], []),
  'buyMultiplier' : IDL.Func([], [], []),
  'buyShield' : IDL.Func([], [], []),
  'getAllLevelProgress' : IDL.Func([], [IDL.Vec(T)], ['query']),
  'getCoins' : IDL.Func([], [IDL.Nat], ['query']),
  'getLevelProgress' : IDL.Func([IDL.Nat], [T], ['query']),
  'getPowerupInventory' : IDL.Func([], [IDL.Nat, IDL.Nat, IDL.Nat], ['query']),
  'spendCoins' : IDL.Func([IDL.Nat], [], []),
  'updateLevelProgress' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Bool], [], []),
  'useDetector' : IDL.Func([], [], []),
  'useMultiplier' : IDL.Func([], [], []),
  'useShield' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const T = IDL.Record({
    'completed' : IDL.Bool,
    'level' : IDL.Nat,
    'stars' : IDL.Nat,
  });
  
  return IDL.Service({
    'addCoins' : IDL.Func([IDL.Nat], [], []),
    'buyDetector' : IDL.Func([], [], []),
    'buyMultiplier' : IDL.Func([], [], []),
    'buyShield' : IDL.Func([], [], []),
    'getAllLevelProgress' : IDL.Func([], [IDL.Vec(T)], ['query']),
    'getCoins' : IDL.Func([], [IDL.Nat], ['query']),
    'getLevelProgress' : IDL.Func([IDL.Nat], [T], ['query']),
    'getPowerupInventory' : IDL.Func(
        [],
        [IDL.Nat, IDL.Nat, IDL.Nat],
        ['query'],
      ),
    'spendCoins' : IDL.Func([IDL.Nat], [], []),
    'updateLevelProgress' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Bool], [], []),
    'useDetector' : IDL.Func([], [], []),
    'useMultiplier' : IDL.Func([], [], []),
    'useShield' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };